---
- name: ISA7 Post Bulid Script
  hosts: isa7stdatabase
  tasks:
  - name: Disble NLA Set Reg Key 1
    ansible.windows.win_regedit:
      path: HKLM:\SYSTEM\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp
      name: SecurityLayer
      data: 0
      type: dword

  - name: Disable NLA Set Reg Key 2
    ansible.windows.win_regedit:
      path: HKLM:\SYSTEM\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp
      name: UserAuthentication
      data: 0
      type: dword

  - name: Set Domain Suffix
    ansible.windows.win_regedit:
      path: HKLM:\SYSTEM\CurrentControlSet\services\Tcpip\Parameters
      name: 'NV Domain'
      data: 'mgt.prvdns.vaultexuk.net'
      type: string

  - name: Set TimeZone to GMT
    ansible.windows.win_powershell:
      script: |
         if ((get-timezone).id -eq 'GMT Standard Time') {
             $Ansible.Changed = $false
         }
         else {
             set-timezone 'GMT Standard Time'
             $Ansible.Changed = $true
         }

  - name: Install Failover-Clustering and management tools
    ansible.windows.win_feature:
      name: Failover-Clustering
      state: present
      include_sub_features: no
      include_management_tools: yes

  - name: Reboot the machine with all defaults
    ansible.windows.win_reboot: