# Ansible Playbook to configure Palo Alto firewall system settings
# 
# This will configure the following:
#
# Interfaces / IP Addressing
# Firewall Zones
# Virtual Router
# Static Routes
# System Settings
 
---
- hosts: '{{ target }}' # Options: test / northampton / wakefield
  connection: local
  vars:
    device:
      ip_address: '{{ ip_address }}'
      username: '{{ username | default(omit) }}'
      password: '{{ password | default(omit) }}'
      api_key: '{{ api_key | default(omit) }}'

  tasks:

    - name: Configure interfaces
      paloaltonetworks.panos.panos_interface:
        provider: '{{ device }}'
        template: '{{ template | default(omit) }}'
        if_name: '{{ item.if_name }}'
        mode: '{{ item.mode }}'
        ip: '{{ item.ip }}'
        enable_dhcp: '{{ item.enable_dhcp }}'
        commit: false
      with_items: '{{ interfaces }}'
      tags: network

    - name: Configure firewall zones
      paloaltonetworks.panos.panos_zone:
        provider: '{{ device }}'
        template: '{{ template | default(omit) }}'
        zone: '{{ item.zone }}'
        mode: '{{ item.mode }}'
        interface: '{{ item.interfaces }}'
      with_items: '{{ zones }}'
      tags: network

    - name: Configure virtual router
      paloaltonetworks.panos.panos_virtual_router:
        provider: '{{ device }}'
        template: '{{ template | default(omit) }}'
        name: '{{ item.name }}'
        interface: '{{ item.interface }}'
        commit: false
      tags: network
      with_items: '{{ virtual_router }}'
      
    - name: Configure static routes
      paloaltonetworks.panos.panos_static_route:
        provider: '{{ device }}'
        template: '{{ template | default(omit) }}'
        virtual_router: 'default'
        name: '{{ item.name }}'
        destination: '{{ item.destination }}'
        nexthop: '{{ item.nexthop }}'
      tags: network
      with_items: '{{ static_routes }}'

    - name: Set device system settings
      paloaltonetworks.panos.panos_mgtconfig:
        provider: '{{ device }}'
        hostname: '{{ hostname }}'
        domain: '{{ domain }}'
        timezone: '{{ timezone }}'
        login_banner: '{{ login_banner }}'
        dns_server_primary: '{{ dns1 }}'
        dns_server_secondary: '{{ dns2 }}'
        ntp_server_primary: '{{ ntp1 }}'
        ntp_server_secondary: '{{ ntp2 }}'